### ISSUE TITLE
Shift+click to belt dupe

### ISSUE THREAD

**Issue by Incurafy** [lilith645/devilutionX_Refined#1]
**Describe**
Moving a potion or scroll from inventory to belt with a full belt with shift+click will duplicate the item when shift+clicking again.

**To Reproduce**
With a full belt: shift+click on a potion or scroll >= once, shift+click anywhere else in inventory.

**Gif**
https://i.imgur.com/zYg6HA6.gif

**Comment by Owlkaline** [comment]
Thanks for that find.

Fixed in commit fda4fa7bc94ffbd873af7d406966506348d6baa1.
